# Generated by Django 6.0.1 on 2026-01-19 08:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('arma', 'Arma'), ('armadura', 'Armadura'), ('medicina', 'Medicina'), ('chatarra', 'Chatarra'), ('municion', 'Munición')], max_length=20, verbose_name='Tipo de objeto')),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('poco_comun', 'Poco Común'), ('raro', 'Raro'), ('legendario', 'Legendario')], default='comun', max_length=20, verbose_name='Rareza')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor en caps')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Peso (kg)')),
                ('danio', models.IntegerField(blank=True, default=0, null=True, verbose_name='Daño (para armas)')),
                ('armadura', models.IntegerField(blank=True, default=0, null=True, verbose_name='Valor de armadura')),
                ('curacion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntos de curación')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'db_table': 'objeto',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Superviviente',
            fields=[
                ('usuario', models.OneToOneField(help_text='Usuario de Django asociado a este superviviente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='superviviente', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
                ('nombre', models.CharField(blank=True, help_text='Nombre en el juego (opcional - si está vacío, usa el nombre del usuario)', max_length=100, null=True, verbose_name='Nombre del personaje')),
                ('apellido', models.CharField(blank=True, help_text='Apellido en el juego (opcional)', max_length=100, null=True, verbose_name='Apellido del personaje')),
                ('numero_vault', models.CharField(default='101', help_text='Vault de origen (ej: 101, 111, 81)', max_length=10, verbose_name='Número de Vault')),
                ('nivel', models.IntegerField(default=1, help_text='Nivel entre 1 y 50', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Nivel del personaje')),
                ('caps', models.IntegerField(default=100, help_text='Moneda del yermo', verbose_name='Caps (dinero)')),
                ('salud', models.IntegerField(default=100, help_text='0-100 (0 = muerto)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntos de salud')),
                ('radiacion', models.IntegerField(default=0, help_text='0-100 (100 = muerte por radiación)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de radiación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Superviviente',
                'verbose_name_plural': 'Supervivientes',
                'db_table': 'superviviente',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel_peligro', models.CharField(choices=[('seguro', 'Seguro'), ('moderado', 'Riesgo Moderado'), ('peligroso', 'Peligroso'), ('mortal', 'Mortal')], default='moderado', max_length=20, verbose_name='Nivel de peligro')),
                ('tiene_comerciantes', models.BooleanField(default=False)),
                ('nivel_radiacion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de radiación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'ordering': ['nivel_peligro', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('superviviente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to='wasteland.superviviente')),
                ('karma', models.CharField(choices=[('santo', 'Santo'), ('bueno', 'Bueno'), ('neutral', 'Neutral'), ('malo', 'Malo'), ('malvado', 'Malvado')], default='neutral', max_length=20, verbose_name='Karma')),
                ('reputacion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('habilidades', models.TextField(blank=True, null=True, verbose_name='Habilidades especiales')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('recompensa_caps', models.IntegerField(default=50, verbose_name='Recompensa en caps')),
                ('dificultad', models.CharField(choices=[('seguro', 'Seguro'), ('moderado', 'Riesgo Moderado'), ('peligroso', 'Peligroso'), ('mortal', 'Mortal')], default='moderado', max_length=20, verbose_name='Dificultad')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('activa', 'Activa'), ('completada', 'Completada'), ('fallida', 'Fallida')], default='disponible', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones', to='wasteland.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misiones',
                'db_table': 'mision',
                'ordering': ['dificultad', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='MisionAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('progreso', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso (%)')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='wasteland.mision')),
                ('superviviente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones_asignadas', to='wasteland.superviviente')),
            ],
            options={
                'verbose_name': 'Misión Asignada',
                'verbose_name_plural': 'Misiones Asignadas',
                'db_table': 'mision_asignada',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('mision', 'superviviente'), name='mision_unica_por_superviviente')],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('equipado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_inventarios', to='wasteland.objeto')),
                ('superviviente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_inventario', to='wasteland.superviviente')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['-fecha_actualizacion'],
                'constraints': [models.UniqueConstraint(fields=('superviviente', 'objeto'), name='objeto_unico_por_superviviente')],
            },
        ),
    ]
